/* automatically generated by rust-bindgen 0.70.1 */

extern "C" {
    pub static ISO_HDLC_TARGET: *const ::std::os::raw::c_char;
}
extern "C" {
    #[doc = " Gets the target build properties (CPU architecture and fine-tuning parameters) for this implementation."]
    pub fn get_iso_hdlc_target() -> *const ::std::os::raw::c_char;
}
extern "C" {
    #[doc = " Calculate CRC-32/ISO_HDLC checksum using hardware acceleration\n\n @param crc0 Initial CRC value (typically 0)\n @param buf Pointer to input data buffer\n @param len Length of input data in bytes\n\n @return Calculated CRC-32/ISO_HDLC checksum"]
    pub fn crc32_iso_hdlc_impl(crc0: u32, buf: *const ::std::os::raw::c_char, len: usize) -> u32;
}
